# Generated by Django 4.1.13 on 2025-03-08 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_estudiante_ultimo_año_cursado'),
        ('trayectos', '0006_trayecto_egresados_trayecto_inicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayectos_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_est', models.CharField(max_length=10)),
                ('name_est', models.CharField(max_length=32)),
                ('seccion', models.CharField(max_length=10)),
                ('trayecto_año', models.CharField(max_length=10)),
                ('codigo_año', models.CharField(max_length=10)),
                ('ref_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
            ],
        ),
    ]
