# Generated by Django 4.1.13 on 2025-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectos', '0007_trayectos_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayectos_all',
            name='apellido_est',
            field=models.CharField(default='N/A', max_length=32),
        ),
    ]
