# Generated by Django 4.1.13 on 2025-03-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectos', '0008_trayectos_all_apellido_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayectos_temp',
            name='apellido_est',
            field=models.CharField(default='N', max_length=32),
        ),
        migrations.AlterField(
            model_name='trayectos_all',
            name='apellido_est',
            field=models.CharField(max_length=32),
        ),
    ]
