# Generated by Django 4.1.13 on 2025-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trayectos', '0009_trayectos_temp_apellido_est_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayectos_temp',
            name='apellido_est',
            field=models.CharField(max_length=32),
        ),
    ]
